server.port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: dog
          uri: https://dog-spring-service.herokuapp.com/ # TODO: need to change
          predicates:
            - Path=/dog/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, *