server.port: ${PORT}
dog.app.url: ${DOG_APP_SERVER}

zuul:
  routes:
    dog:
      path: /api/dogs/**
      url: ${DOG_SERVICE_URL}/dogs


#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: dogService
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/api/dog/**
#          filters:
#            - AddResponseHeader=Access-Control-Allow-Origin, *